name: PWA Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Start local server
      run: |
        python -m http.server 8000 &
        sleep 5
    
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v9
      with:
        urls: |
          http://localhost:8000/
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: ./lighthouserc.json
      
    - name: Check PWA score
      run: |
        score=$(cat .lighthouseci/lhr-*.json | jq '.categories.pwa.score')
        if (( $(echo "$score < 0.9" | bc -l) )); then
          echo "PWA score $score is below threshold of 0.9"
          exit 1
        fi
